name: 'Trigger Docker Hub'
# env:
#    DOCKERHUB_WEBHOOK: ${{secrets.DOCKERHUB_WEBHOOK}}
on: push
  # schedule:
  #   - cron: '0 21 * * 0'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X ${{secrets.DOCKERHUB_WEBHOOK}}
